### ISSUE TITLE
How could we run Cutmix + shakedrop

### ISSUE THREAD

**Issue by 3DHM** [clovaai/CutMix-PyTorch#12]
Hi, I am wondering have you implemented the code for cutmix + shakedrop? Would like to try it, it would be very helpful!

Thanks so much!

**Comment by hellbell** [comment]
@hannahlee66 
If you get some codes for shakedrop (e.g., https://github.com/owruby/shake-drop_pytorch), then it will be straightforward to conduct of cutmix + shakedrop.

**Comment by 3DHM** [comment]
Thanks for the answer! But I am wondering how could we test the trained model using cutmix+shakedrop? Seems there is no cutmix+shakedrop model provided in your folders.

**Comment by hellbell** [comment]
@hannahlee66 
The model file can be downloaded here: [[model]](https://www.dropbox.com/sh/cs0o0rcyant3xv8/AADnd15p-p7PBS03a9KT02yha?dl=0).
Again, you may adjust your codes with the shakedrop codes.

**Comment by 3DHM** [comment]
Is it a consistent match?  I am not sure if it is ok for you to release your shake drop test codes......

**Comment by hellbell** [comment]
@hannahlee66 
Sorry, I cannot right now. 
But I am planning to update our codes with major extensions soon, so I will add that feature then. 
Thanks!
