### ISSUE TITLE
How about fine-tuning  on COCO detection?

### ISSUE THREAD

**Issue by GengDavid** [clovaai/CutMix-PyTorch#13]
Thanks for your great work! Have you tried to use CuiMix pre-trained model on the COCO detection task and how about the results?

**Comment by hellbell** [comment]
@GengDavid 
We have tried CutMix-pretrained model on MS-COCO detection task whose framework and backbone are Faster-RCNN and ResNet-50, respectively. 

Results of ResNet50-Faster-RCNN:

Backbone  | mAP
-- | --
Baseline | 33.27
Mixup-Pretrained  | 34.18
Cutout-Pretrained   | 34.28
CutMix-Pretrained   | **35.16**

CutMix-Pretrained shows a meaningful improvement in MS-COCO detection!

**Comment by GengDavid** [comment]
Excited to know that! Thanks 😄
