### ISSUE TITLE
why should set `requires_grad` True

### ISSUE THREAD

**Issue by FantDing** [clovaai/CutMix-PyTorch#15]
https://github.com/clovaai/CutMix-PyTorch/blob/e54b8387ad6f63d2b9cb2c1f9dc332aad2d185e1/train.py#L242

**Comment by hellbell** [comment]
@FantDing 
That was a legacy of pytorch version 0.3. 
We updated our code for the newer version of pytorch (>1.0) by fixing those legacies.
