### ISSUE TITLE
question of why cutmix has improved performance.

### ISSUE THREAD

**Issue by seominseok0429** [clovaai/CutMix-PyTorch#16]
hi author. 

I'm a student studying deep learning in South Korea.

If look at your paper and the code, it seems like you are cropping random locations, mixing two images and matching two labels.

The question arises here. For example, if there are no objects in an image that is cropped at random locations, label noise may be generated, which may adversely affect performance.

Why does this not adversely affect performance?

**Comment by hellbell** [comment]
@seominseok0429 

> The question arises here. For example, if there are no objects in an image that is cropped at random locations, label noise may be generated, which may adversely affect performance.
> Why does this not adversely affect performance?

In general, when a cropped image has no object at all, the mixing ratio (lambda) will be very small, so it would work as a label noise effect. Also, even though the cropped image doesn't have any object, it has some contexts to classify its class (e.g., a water patch for sea turtle category), and thus we guess this context information boosts classification accuracy.

**Comment by seominseok0429** [comment]
친절한 답변 정말 감사합니다!

**Comment by hellbell** [comment]
@seominseok0429 Thanks :) Closing this issue.
