### ISSUE TITLE
Aplha  for cutmix

### ISSUE THREAD

**Issue by mobassir94** [clovaai/CutMix-PyTorch#20]
for my dataset how do i  choose value of alpha  for cutmix to get best performance?

**Comment by hellbell** [comment]
@mobassir94 
It depends on the dataset type, model size, etc.

In my experience, usually `alpha=1` works well for many datasets.
But when we use small datasets or small models, a small alpha (e.g., ~0.2) works better than a larger one. 

So I would like to recommend that if you have computational resources to try the same experiments several times, try two or three alphas (e.g., 1.0, 0.5, 0.2) and find the best one.
