### ISSUE TITLE
some problems about the parameters

### ISSUE THREAD

**Issue by ReverseSystem001** [clovaai/CutMix-PyTorch#23]
thanks for your amazing paper . follow the paper. I set the beta = 1.  what number the cutmix_prob should i set?

**Comment by hellbell** [comment]
@ReverseSystem001 
`cutmix_prob` is set to `1.0` in the default setting and it usually works well.
Empirically, we set it to `0.5` or lower when the network is lightweight, such as `mobilenet`, but it depends on what dataset is used.
