### ISSUE TITLE
Could you please to figure out how to train on Pascal VOC?

### ISSUE THREAD

**Issue by aimhabo** [clovaai/CutMix-PyTorch#29]
We are interesting to use cutmix in object detection. But the problem is that whats the bbox drop rule?

**Comment by ShihuaiXu** [comment]
哥  我也想把这个做到检测数据里面 我的qq是531232693 加个qq一起探讨一下呗

**Comment by hellbell** [comment]
Hi, we didn't try CutMix on the detection task directly.
The same q&a is here: #19 (comment)
