### ISSUE TITLE
Reason for using random region only in 'mini-batch'

### ISSUE THREAD

**Issue by ildoonet** [clovaai/CutMix-PyTorch#3]
If we use random regions of data from full dataset, Can it improve the performance further?

Have you experimented this?

(currently, random regions are sampled from 'mini-batch')

**Comment by hellbell** [comment]
@ildoonet 
It is a good question. Unfortunately, we didn't experiment that. 
Currently, we consider the efficiency for loading image data, so the random region is selected only in the 'mini-batch'. 
It might improve the performance by using outside the 'mini-batch' data, but I guess there is no big difference if we use sufficiently large mini-batch size (we use 256). 
I will be very happy if you test and verify this. :)
Thanks!
