### ISSUE TITLE
Have you tried using feature-level CutMix and image-level CutMix at the same time?

### ISSUE THREAD

**Issue by vozhuo** [clovaai/CutMix-PyTorch#31]
In 'Ablation Studies',  you applied CuMix on different feature levels, have you tried to apply it on both feature-level and image-level at the same time?

**Comment by hellbell** [comment]
Hi, we didn't try that :( 
but I guess it would show a similar performance as feature-level CutMix.

**Comment by vozhuo** [comment]
Thank you.
