### ISSUE TITLE
what should I change to use this concept on my data set

### ISSUE THREAD

**Issue by Oussamab21** [clovaai/CutMix-PyTorch#41]
Thanks for sharing the code I was wondering what should I change to use this concept on my own data set and along side with the mixup concept presented in this reposotory
https://github.com/facebookresearch/mixup-cifar10
thanks in advance

**Comment by hellbell** [comment]
Hi, our implementation is quite simple, 
so I think you might have to see the CutMix training parts (https://github.com/clovaai/CutMix-PyTorch/blob/master/README.md#experiments) and apply them on your own training code.

**Comment by Oussamab21** [comment]
Hi , thank you I saw that but i was wondering how this can cope with the Mixup concept does this needs further changes ? or they can work along with no further updates?

**Comment by hellbell** [comment]
Sorry, I can't understand the mixup concept, but anyway I think there are no further changes to apply CutMix.
