### ISSUE TITLE
Using with DropBlock

### ISSUE THREAD

**Issue by ghost** [clovaai/CutMix-PyTorch#8]
Hello, Firstly, I really appreciate to publish good paper and open the source code!

My question is, as I write on the title, what can be happen if I use CutMix with DropBlock?
Do you think that it is helpful? or there can be some interference between to techniques?

**Comment by hellbell** [comment]
@Seojii 
We didn't try `CutMix+DropBlock` so it is hard to say it would work well or not before we observe the results.
But with my experience of using `CutMix+Cutout`, which is somewhat similar to `CutMix+DropBlock`, the performance was not better than using `CutMix`. 
My conjecture is that `Cutout` or `Dropblock` are kinds of regional dropout and `CutMix` implicitly includes the regional dropout concept, therefore, those kinds of combinations would be not much effective.
