### ISSUE TITLE
Another reimplementation

### ISSUE THREAD

**Issue by ildoonet** [clovaai/CutMix-PyTorch#9]
I got BIG interest on your work so I decided to reimplement with some fixes. 

Issue #1 #3 #4 are dealt with this new reimplementation and I still work on improving for better usability and performance.

Currently, after I fixed those issues, I got clearly-improved results on CIFAR100.

|                                 | Top-1 Error(@300epoch) | Top-1 Error(Best) |
|---------------------------------|------------:|------------|
| Paper's Reported Result         | N/A         | 13.81      |
| Our Re-implementation           | 13.68       | 13.15      |

I will update as other experiments are updated my implementation progressed. 

Repo : https://github.com/ildoonet/cutmix

**Comment by hellbell** [comment]
@ildoonet 
Good. 
Please let me know the ImageNet results. 
You can send me PR for the implementation. 
Thanks!

**Comment by ildoonet** [comment]
Here is my imagenet experiment result.

|                                 | Top-1 Error(@300epoch) | Top-1 Error(Best) |
|---------------------------------|------------:|-----------:|
| Paper's Reported Result         | N/A         | 21.4      |
| Author's Code(Our Re-run)       | 21.768      | 21.586    |
| Our Re-implementation           | 21.524      | 21.340    |

I use your code without modification to replication the paper's result, but I got slightly worse results(21.586). It could be from different environment or other things.

But to me, it is clear that dealing with issues #1 #3 #4 is good for the final performance.

**Comment by hellbell** [comment]
@ildoonet 
Great! It is very happy to see another SOTA result of CutMix from you. 
I will verify the modification of #3 and #4 and apply to our code.
Thanks again :)

**Comment by hellbell** [comment]
Closing the issue.
